linters:
  stylelint:
    config: 'stylelint.config.js'
    ignore: 'box-model,ids'
files:
  ignore: 
    - 'css/dgstrap.css*'
    - 'css/dgstrap.min.css*'
    - 'css/styles.css*'
    - 'css/_grids.scss*'